/**
 * Syntax rules for TypeScript-family and web-focused languages.
 */

import type { LanguageRules } from "./syntax.js";

const TYPESCRIPT_RULES: LanguageRules = {
	keywords: new Set([
		"const",
		"let",
		"var",
		"function",
		"class",
		"return",
		"if",
		"else",
		"for",
		"while",
		"do",
		"switch",
		"case",
		"break",
		"continue",
		"new",
		"delete",
		"typeof",
		"instanceof",
		"in",
		"of",
		"try",
		"catch",
		"finally",
		"throw",
		"async",
		"await",
		"yield",
		"import",
		"export",
		"from",
		"default",
		"as",
		"extends",
		"implements",
		"interface",
		"type",
		"enum",
		"namespace",
		"abstract",
		"private",
		"protected",
		"public",
		"static",
		"readonly",
		"override",
		"satisfies",
		"declare",
		"true",
		"false",
		"null",
		"undefined",
		"void",
		"never",
		"this",
		"super",
	]),
	typeKeywords: new Set([
		"string",
		"number",
		"boolean",
		"object",
		"symbol",
		"bigint",
		"any",
		"unknown",
		"Array",
		"Map",
		"Set",
		"Promise",
		"Record",
		"Partial",
		"Required",
		"Readonly",
	]),
	lineComment: "//",
	blockCommentStart: "/*",
	blockCommentEnd: "*/",
	stringDelimiters: ['"', "'", "`"],
	operators: /^(?:===|!==|=>|&&|\|\||[+\-*/%=<>!&|^~?:]+)/,
};

const BASH_RULES: LanguageRules = {
	keywords: new Set([
		"if",
		"then",
		"else",
		"elif",
		"fi",
		"for",
		"while",
		"do",
		"done",
		"case",
		"esac",
		"in",
		"function",
		"return",
		"exit",
		"local",
		"export",
		"source",
		"alias",
		"unalias",
		"set",
		"unset",
		"shift",
		"break",
		"continue",
		"declare",
		"readonly",
		"typeset",
		"eval",
		"exec",
		"trap",
		"wait",
		"true",
		"false",
	]),
	typeKeywords: new Set([]),
	lineComment: "#",
	blockCommentStart: "",
	blockCommentEnd: "",
	stringDelimiters: ['"', "'"],
	operators: /^(?:\|\||&&|;;|[|&<>!;=]+)/,
};

const JSON_RULES: LanguageRules = {
	keywords: new Set(["true", "false", "null"]),
	typeKeywords: new Set([]),
	lineComment: "",
	blockCommentStart: "",
	blockCommentEnd: "",
	stringDelimiters: ['"'],
	operators: /^[:]/,
};

const YAML_RULES: LanguageRules = {
	keywords: new Set(["true", "false", "null", "yes", "no", "on", "off"]),
	typeKeywords: new Set([]),
	lineComment: "#",
	blockCommentStart: "",
	blockCommentEnd: "",
	stringDelimiters: ['"', "'"],
	operators: /^[:\-|>]/,
};

const HTML_RULES: LanguageRules = {
	keywords: new Set([
		"html",
		"head",
		"body",
		"div",
		"span",
		"p",
		"a",
		"img",
		"ul",
		"ol",
		"li",
		"table",
		"tr",
		"td",
		"th",
		"form",
		"input",
		"button",
		"select",
		"option",
		"h1",
		"h2",
		"h3",
		"h4",
		"h5",
		"h6",
		"script",
		"style",
		"link",
		"meta",
		"title",
		"header",
		"footer",
		"nav",
		"main",
		"section",
		"article",
		"aside",
	]),
	typeKeywords: new Set([]),
	lineComment: "",
	blockCommentStart: "<!--",
	blockCommentEnd: "-->",
	stringDelimiters: ['"', "'"],
	operators: /^[=<>/]+/,
};

const CSS_RULES: LanguageRules = {
	keywords: new Set([
		"display",
		"position",
		"color",
		"background",
		"margin",
		"padding",
		"border",
		"font",
		"width",
		"height",
		"top",
		"left",
		"right",
		"bottom",
		"flex",
		"grid",
		"align",
		"justify",
		"transform",
		"transition",
		"animation",
		"none",
		"auto",
		"inherit",
		"initial",
		"unset",
		"important",
	]),
	typeKeywords: new Set([]),
	lineComment: "",
	blockCommentStart: "/*",
	blockCommentEnd: "*/",
	stringDelimiters: ['"', "'"],
	operators: /^[:;{}]+/,
};

export const WEB_LANGUAGE_MAP: Record<string, LanguageRules> = {
	typescript: TYPESCRIPT_RULES,
	ts: TYPESCRIPT_RULES,
	javascript: TYPESCRIPT_RULES,
	js: TYPESCRIPT_RULES,
	tsx: TYPESCRIPT_RULES,
	jsx: TYPESCRIPT_RULES,
	bash: BASH_RULES,
	sh: BASH_RULES,
	shell: BASH_RULES,
	zsh: BASH_RULES,
	json: JSON_RULES,
	yaml: YAML_RULES,
	yml: YAML_RULES,
	html: HTML_RULES,
	htm: HTML_RULES,
	xml: HTML_RULES,
	css: CSS_RULES,
	scss: CSS_RULES,
};
